float:
  any:
  - base_args: ['@metric']
    constructor: HnswPPLib
    disabled: false
    docker_tag: ann-benchmarks-hnswpplib
    module: ann_benchmarks.algorithms.hnswpplib
    name: hnswpplib
    run_groups:
      M-12:
        arg_groups: [{M: 12, efConstruction: 500}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
      M-64:
        arg_groups: [{M: 64, efConstruction: 500}]
        args: {}
        query_args: [[10, 20, 40, 80, 120, 200, 400, 600, 800]]
